services:
  - type: cron
    name: selenium-script
    schedule: "0 15 * * *"  # 9 AM CDMX
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: PROD
        sync: false
