name: Scraping con Selenium

on:
  schedule:
    - cron: '0 1 * * *'  # todos los días a las 1 AM UTC
  workflow_dispatch:     # permite ejecutarlo manualmente

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Google Chrome compatible
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Instalar dependencias de Python
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: DEBUG: imprimir variables de entorno
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
          echo "BUCKET_NAME=$BUCKET_NAME"

      - name: Ejecutar script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          python3 genera_informacion.py
